params:
  - group: Parameters
    items:
      - key: data
        name: Data
        type: array
        element:
          type: object
        ui: input
events:
  - key: onNodeSelect
    name: onNodeSelect
    args:
      - name: node
        type: object
        required: true