params:
  - group: Parameters
    items:
      - key: dataTree
        name: dataTree
        type: tree
        ui: json-editor
        defaultValue:
          - id: "1"
            name: "CRD"
            label: custom-label 
            color: "blue"
            children:
              - id: "1-1"
                name: "CRD"
                children:
                  - id: "1-1-1"
                    name: "CRD"
                  - id: "1-1-2"
                    name: "CRD"
              - id: "1-2"
                name: "CRD"
          - id: "2"
            name: "CRD"
            children:
              - id: "2-1"
                name: "CRD"
              - id: "2-2"
                name: "CRD"
      - key: customNodes
        name: customNodes
        type: array
        element:
          type: object
          items:
            - key: name
              name: name
              type: string
              ui: input
              defaultValue: ""
            - key: color
              name: color
              type: string
              ui: input
              defaultValue: ""
            - key: icon
              name: icon
              type: string
              ui: input
              defaultValue: ""
            - key: next
              name: next
              type: string
              ui: input
              defaultValue: ""
        ui: list-editor
        defaultValue:
          - name: "CRD"
            color: "rgb(92,191,142)"
            icon: "<path fill='white' d='M13.28 7.6h-.7V5.76c0-.51-.41-.93-.92-.93H9.81v-.7a1.16 1.16 0 00-2.3 0v.7H5.65c-.51 0-.92.42-.92.93V7.5h.69a1.25 1.25 0 010 2.5h-.7v1.75c0 .5.42.92.93.92H7.4V12a1.25 1.25 0 012.5 0v.7h1.75c.5 0 .92-.42.92-.93V9.91h.7a1.16 1.16 0 000-2.3z'/>"
          - name: "POD"
            icon: "<g fill='white' fill-rule='evenodd'><path d='M5.4 5.9l3.6-1 3.6 1-3.6 1zM5.4 6.3V10L8.8 12V7.3zM12.6 6.3V10L9.3 12V7.3z'/></g>"
          - name: "NS"
            icon: "<path fill='none' stroke='white' stroke-dasharray='.8 .4' stroke-dashoffset='3.44' stroke-linejoin='round' stroke-miterlimit='10' stroke-width='.4' d='M5.18 5.2h7.67v6.69H5.18z'/>"
          - name: "DEPLOY"
            icon: "<g fill='white' fill-rule='evenodd'><path d='M5.4 5.9l3.6-1 3.6 1-3.6 1zM5.4 6.3V10L8.8 12V7.3zM12.6 6.3V10L9.3 12V7.3z'/></g>"
          - name: "SVC"
            icon: "<g fill='white' fill-rule='evenodd'><path d='M8.58 12.56a4.45 4.45 0 114.23-4.73l-1.76.11A2.69 2.69 0 108.5 10.8z'/><path d='M9.49 7.83l1.4 3.43 3.22-3.43z'/></g>"
          - name: "ING"
            icon: "<path fill='white' d='M11.77 12.54H9.49L4.57 6.4H3.15V4.37h2.31l4.93 6.16h1.38v-1.6l3.12 2.6-3.12 2.6zM9.29 7.8l1.1-1.38h1.38v1.6l3.12-2.6-3.12-2.6V4.4H9.49L8.04 6.22zm-3.6 1.36l-1.12 1.4H3.15v2.02h2.31l1.48-1.85z' pointer-events='none'/>"
      - key: hideMimiMap
        name: hideMimiMap
        type: string
        ui: select
        options:
          - show
          - hide
        defaultValue: show
      - key: hidePanel
        name: hidePanel
        type: string
        ui: select
        options:
          - show
          - hide
        defaultValue: show
events:
  - key: onNodeSelect
    name: onNodeSelect
    args:
      - name: node
        type: object
        required: false
  - key: onGroupSelect
    name: onGroupSelect
    args:
      - name: node
        type: object
        required: false
  - key: onNodeDoubleClick
    name: onNodeDoubleClick
    args:
      - name: node
        type: object
        required: false
  - key: onSave
    name: onSave
    args:
      - name: node
        type: object
        required: false