params:
  - group: Parameters
    items:
      - key: data
        name: Data
        type: object
        ui: input
      - key: customNodes
        name: Data
        type: array
        element:
          type: object
        ui: input
        defaultValue:
          - 
      - key: hideMimiMap
        name: hideMimiMap
        type: string
        ui: select
        options:
          - show
          - hide
        defaultValue: show
      - key: hidePanel
        name: hidePanel
        type: string
        ui: select
        options:
          - show
          - hide
        defaultValue: view
events:
  - key: onNodeSelect
    name: onNodeSelect
    args:
      - name: node
        type: object
        required: false
  - key: onNodeDoubleClick
    name: onNodeDoubleClick
    args:
      - name: node
        type: object
        required: false
  - key: onSave
    name: onSave
    args:
      - name: node
        type: object
        required: false